name: Build Registre Ecole

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        # Pour aussi générer une version Mac ou Linux, décommente :
        # os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances
        run: npm install

      - name: Construire l'application
        run: npx electron-builder --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
